--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J1b1x/MapVideoExample
build-by-default: true
branches:
- master
projects:
  MapVideoExample:
    path: ""
    libs:
      - src: Jibix/MapVideo/MapVideo
        version: ^0.0.1
...
